version: '3.7'
services:
  nodejs-api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "npm install; nodemon index.ts --color=always"
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    container_name: nodejs-api
    networks:
      - app
    links:
      - mongo-db
  mongo-db:
    image: mongo:latest
    command: mongod --port 27018
    ports:
      - "27018:27018"
    container_name: mongo-db
    volumes:
      - ./data/:/data/db
    networks:
      - app
networks:
    app:
        driver: bridge